export const contacts = [
  {name: 'Abdoulaye Ndoye', chat: 'Hello there'},
  {name: 'Cheikh Ndoye', chat: 'This is a great app'},
  {name: 'Abdoulaye Ndiaye', chat: "you'll se "},
  {name: 'Cheikh Ndoye', chat: 'I feeel very confident about it'},
  {name: 'Abdoulaye Ndoye', chat: 'Hello there'},
  {name: 'Cheikh Ndoye', chat: 'This is a great app'},
  {name: 'Abdoulaye Ndiaye', chat: "you'll se "},
  {name: 'Cheikh Ndoye', chat: 'I feeel very confident about it'},
  {name: 'Abdoulaye Ndoye', chat: 'Hello there'},
  {name: 'Cheikh Ndoye', chat: 'This is a great app'},
  {name: 'Abdoulaye Ndiaye', chat: "you'll se "},
  {name: 'Cheikh Ndoye', chat: 'I feeel very confident about it'},
  {name: 'Abdoulaye Ndoye', chat: 'Hello there'},
  {name: 'Cheikh Ndoye', chat: 'This is a great app'},
  {name: 'Abdoulaye Ndiaye', chat: "you'll se "},
  {name: 'Cheikh Ndoye', chat: 'I feeel very confident about it'},
  {name: 'Abdoulaye Ndoye', chat: 'Hello there'},
  {name: 'Cheikh Ndoye', chat: 'This is a great app'},
  {name: 'Abdoulaye Ndiaye', chat: "you'll se "},
  {name: 'Cheikh Ndoye', chat: 'I feeel very confident about it'},
  {name: 'Abdoulaye Ndoye', chat: 'Hello there'},
  {name: 'Cheikh Ndoye', chat: 'This is a great app'},
  {name: 'Abdoulaye Ndiaye', chat: "you'll se "},
  {name: 'Cheikh Ndoye', chat: 'I feeel very confident about it'},
  {name: 'Abdoulaye Ndoye', chat: 'Hello there'},
  {name: 'Cheikh Ndoye', chat: 'This is a great app'},
  {name: 'Abdoulaye Ndiaye', chat: "you'll se "},
  {name: 'Cheikh Ndoye', chat: 'I feeel very confident about it'},
  {name: 'Abdoulaye Ndoye', chat: 'Hello there'},
  {name: 'Cheikh Ndoye', chat: 'This is a great app'},
  {name: 'Abdoulaye Ndiaye', chat: "you'll se "},
  {name: 'Cheikh Ndoye', chat: 'I feeel very confident about it'},
  {name: 'Abdoulaye Ndoye', chat: 'Hello there'},
  {name: 'Cheikh Ndoye', chat: 'This is a great app'},
  {name: 'Abdoulaye Ndiaye', chat: "you'll se "},
  {name: 'Cheikh Ndoye', chat: 'I feeel very confident about it'},
  {name: 'Abdoulaye Ndoye', chat: 'Hello there'},
  {name: 'Cheikh Ndoye', chat: 'This is a great app'},
  {name: 'Abdoulaye Ndiaye', chat: "you'll se "},
  {name: 'Cheikh Ndoye', chat: 'I feeel very confident about it'},
  {name: 'Abdoulaye Ndoye', chat: 'Hello there'},
  {name: 'Cheikh Ndoye', chat: 'This is a great app'},
  {name: 'Abdoulaye Ndiaye', chat: "you'll se "},
  {name: 'Cheikh Ndoye', chat: 'I feeel very confident about it'},
  {name: 'Abdoulaye Ndoye', chat: 'Hello there'},
  {name: 'Cheikh Ndoye', chat: 'This is a great app'},
  {name: 'Abdoulaye Ndiaye', chat: "you'll se "},
  {name: 'Cheikh Ndoye', chat: 'I feeel very confident about it'},
  {name: 'Abdoulaye Ndoye', chat: 'Hello there'},
  {name: 'Cheikh Ndoye', chat: 'This is a great app'},
  {name: 'Abdoulaye Ndiaye', chat: "you'll se "},
  {name: 'Cheikh Ndoye', chat: 'I feeel very confident about it'},
  {name: 'Abdoulaye Ndoye', chat: 'Hello there'},
  {name: 'Cheikh Ndoye', chat: 'This is a great app'},
  {name: 'Abdoulaye Ndiaye', chat: "you'll se "},
  {name: 'Cheikh Ndoye', chat: 'I feeel very confident about it'},
  {name: 'Abdoulaye Ndoye', chat: 'Hello there'},
  {name: 'Cheikh Ndoye', chat: 'This is a great app'},
  {name: 'Abdoulaye Ndiaye', chat: "you'll se "},
  {name: 'Cheikh Ndoye', chat: 'I feeel very confident about it'},
];
